name: xfan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.6.1
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  firebase_storage: ^11.6.9
  js: ^0.6.7
  share_plus: ^6.3.1
  flutter_local_notifications: ^14.1.1
  permission_handler: ^11.1.0
  path_provider: ^2.1.2
  path: ^1.8.3
  camera: ^0.10.5+9
  image_picker: ^1.0.7


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
