// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfuNNKYujBmcyMLOBW4Ftmy5f_LcyQWDg',
    appId: '1:701468395137:web:8e0cd11207af120e66ef80',
    messagingSenderId: '701468395137',
    projectId: 'xfan-ef312',
    authDomain: 'xfan-ef312.firebaseapp.com',
    storageBucket: 'xfan-ef312.firebasestorage.app',
    measurementId: 'G-803VYFM400',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkU8PXclZiGi8iTffeXvfWAF3h2jbvzPk',
    appId: '1:701468395137:android:abfa50639797119d66ef80',
    messagingSenderId: '701468395137',
    projectId: 'xfan-ef312',
    storageBucket: 'xfan-ef312.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmMlSj6g7AMs1hocjBouiw7OdQmw6TU-I',
    appId: '1:701468395137:ios:ecfa5dc216ca159c66ef80',
    messagingSenderId: '701468395137',
    projectId: 'xfan-ef312',
    storageBucket: 'xfan-ef312.firebasestorage.app',
    iosBundleId: 'com.example.xfan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmMlSj6g7AMs1hocjBouiw7OdQmw6TU-I',
    appId: '1:701468395137:ios:ecfa5dc216ca159c66ef80',
    messagingSenderId: '701468395137',
    projectId: 'xfan-ef312',
    storageBucket: 'xfan-ef312.firebasestorage.app',
    iosBundleId: 'com.example.xfan',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfuNNKYujBmcyMLOBW4Ftmy5f_LcyQWDg',
    appId: '1:701468395137:web:a8155acf1ba3ef6366ef80',
    messagingSenderId: '701468395137',
    projectId: 'xfan-ef312',
    authDomain: 'xfan-ef312.firebaseapp.com',
    storageBucket: 'xfan-ef312.firebasestorage.app',
    measurementId: 'G-LBRJNMJ6KF',
  );
}
